function normStructArray = createNormalizeStruct( ...
	expStructArray , normConditionStr )
%CREATE_NORMALIZE_STRUCT initializes empty structs for data in preparation
%for the normalization to WT process
%   The structs are dummy, temporary structures to store the data while it
%   is being normalized.

expN = length(expStructArray);
normCondN = length(normConditionStr);

normalizeTemplate = struct(...
			'condition',{{}}...
			,'normCondition',''...
			,'cellLocation',{{}}...
			,'yelMembrane',[]...
			,'yelEntire',[]...
			,'redEntire',[]...
			,'yelMembraneAbsolute',[]...
			,'yelEntireAbsolute',[]...
			,'redEntireAbsolute',[]...
			,'memDens',[]...
			,'logMemDens',[]);

		
for k=1:normCondN
	currentNormCond = normConditionStr{k};
	for j=1:expN

		expStruct = expStructArray(j);

		normStruct = normalizeTemplate;
		normStruct.normCondition = currentNormCond;

		for i=1:length(expStruct.imageLocal)

			cellN = expStruct.imageLocal(i).cellN(end);
			tmpCondition(1:cellN,1) = {expStruct.imageLocal(i).condition};
			normStruct.condition = ...
				vertcat(normStruct.condition,tmpCondition);

			clear tmpCondition

			normStruct.cellLocation = vertcat(normStruct.cellLocation...
				,expStruct.imageLocal(i).cellLocation);
			normStruct.yelMembrane = vertcat(normStruct.yelMembrane...
				,expStruct.imageLocal(i).yelMembrane);
			normStruct.yelEntire = vertcat(normStruct.yelEntire...
				,expStruct.imageLocal(i).yelEntire);
			normStruct.redEntire = vertcat(normStruct.redEntire...
				,expStruct.imageLocal(i).redEntire);
			normStruct.yelMembraneAbsolute = ...
				vertcat(normStruct.yelMembraneAbsolute...
				,expStruct.imageLocal(i).yelMembraneAbsolute);	
			normStruct.yelEntireAbsolute = ...
				vertcat(normStruct.yelEntireAbsolute...
				,expStruct.imageLocal(i).yelEntireAbsolute);
			normStruct.redEntireAbsolute = ...
				vertcat(normStruct.redEntireAbsolute...
				,expStruct.imageLocal(i).redEntireAbsolute);


		end
		
		normStructArray((k-1)*expN + j) = normStruct;

	end
	
end

end
