function normStructArray = createNormalizeStruct( plateStructArray )
%CREATE_NORMALIZE_STRUCT initializes empty structs for data in preparation
%for the normalization to WT process
%   The structs are dummy, temporary structures to store the data while it
%   is being normalized.

plateN = length(plateStructArray);

normalizeTemplate = struct(...
			'mutation',{{}}...
			,'temp',{{}}...
			,'cellLocation',[]...
			,'yelEntire',[]...
			,'yelMembrane',[]...
			,'redEntire',[]...
			,'yelMembraneAbsolute',[]...
			,'yelEntireAbsolute',[]...
			,'memDens',[]...
			,'logMemDens',[]...			
			,'normMemDens',[]...
			,'logNormMemDens',[]);

for j=1:plateN
	
	plateStruct = plateStructArray(j);
	normStructArray(j) = normalizeTemplate;
	
	for i=1:length(plateStruct.imageLocal)
		
		cellN = plateStruct.imageLocal(i).cellN(end);
		tmp(1:cellN,1) = {plateStruct.imageLocal(i).mutation};
		normStructArray(j).mutation = vertcat(normStructArray(j).mutation,tmp);
		normStructArray(j).temp = vertcat(normStructArray(j).temp,tmp);
		
		clear tmp
		
		normStructArray(j).cellLocation = vertcat(normStructArray(j).cellLocation...
			,plateStruct.imageLocal(i).cellLocation);
		normStructArray(j).yelEntire = vertcat(normStructArray(j).yelEntire...
			,plateStruct.imageLocal(i).yelEntire);
		normStructArray(j).yelMembrane = vertcat(normStructArray(j).yelMembrane...
			,plateStruct.imageLocal(i).yelMembrane);
		normStructArray(j).redEntire = vertcat(normStructArray(j).redEntire...
			,plateStruct.imageLocal(i).redEntire);
		normStructArray(j).memDens = vertcat(normStructArray(j).memDens...
			,plateStruct.imageLocal(i).memDens);
		normStructArray(j).logMemDens = vertcat(normStructArray(j).logMemDens...
			,plateStruct.imageLocal(i).logMemDens);
		
				normStructArray(j).yelMembraneAbsolute = vertcat(normStructArray(j).yelMembraneAbsolute...
			,plateStruct.imageLocal(i).yelMembraneAbsolute);	
				normStructArray(j).yelEntireAbsolute = vertcat(normStructArray(j).yelEntireAbsolute...
			,plateStruct.imageLocal(i).yelEntireAbsolute);		
	end
	
end
end