function  imageStruct = createImageStruct( redPathArray , yelPathArray )
%CREATECONDITIONS create empty structs for each conditions as listed in
%'conditionsStr'

pathN = length(redPathArray);
imageTemplate = struct(...
			'redPath',''...
			,'yelPath',''...
			,'boundingBox',[] ...
			,'cellWidth',[] ...
			,'cellLength',[] ...
			,'meanInsideCell',[]...
			,'meanOutsideCell',[]...
			,'meanMembrane',[]...
			,'ratioOutsideInside',[]...
			,'ratioMembraneInside',[]...
			,'yelBackground',[]...
			,'cellN',[] ...
			);

imageStruct(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStruct(i).redPath = redPathArray{i};
	imageStruct(i).yelPath = yelPathArray{i};
end

end

