function  conditions = createConditions( conditionsStr )
%CREATECONDITIONS create empty structs for each conditions as listed in
%'conditionsStr'

conditionsN = length(conditionsStr);
conditionTemplate = struct(...
			'mutation',[]...
			,'wells',{{}} ...
			,'redFiles',{{}} ... 
			,'yelFiles',{{}} ...
			,'redImages',[] ... 
			,'yelImages',[] ...
            ,'redCells',{{}} ...
			,'yelCells',{{}});

for i=1:conditionsN
	conditions(i) = conditionTemplate;
	conditions(i).mutation = conditionsStr(i);
	
end

end

