function  exp = createExperimentStruct( experimentN )
%CREATEEXPERIMENTS create empty structs for each experiment.

experimentTemplate = struct(...
			'expStr',[]...
			,'baseFolder',[]...
			,'local_quench',[]...
			,'filePrefix',[]...
			,'conditionStr',{{}} ...
			,'condWells',{{}}...
			,'condWellsControl',{{}}...
		);

for i=1:experimentN
	
	exp(i) = experimentTemplate;
	
end

end
