function imageStructArray = createImageQuenchStruct(...
	mutationArray,test_controlArray...
	,redPathArray,yelPathArray)
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here

pathN = size(redPathArray,1);

imageTemplate = struct(...
			'mutation',''...
			,'test_control',''...
			,'redPath',{{}}...
			,'yelPath',{{}}...
			,'yelInsideOverT',[]...
			,'redMaskChange',[]...
			,'maxGradIodine',[]...
			,'maxGradLocation',[]...
			);

imageStructArray(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStructArray(i).mutation = mutationArray{i};
	imageStructArray(i).test_control = test_controlArray{i};
	imageStructArray(i).redPath = redPathArray(i,:);
	imageStructArray(i).yelPath = yelPathArray(i,:);
end

end

