function wellStructArray = createWellStruct(...
	conditionArray,test_controlArray,timelineArray...
	,timeStepArray,redPathArray,yelPathArray)
%CREATE_WELL_STRUCT initializes empty struct for each quench well
%   Defines all attributes of well struct and assigns initial data
%   to appropriate attributes.

pathN = size(redPathArray,1);

imageTemplate = struct(...
			'conditionStr',''...
			,'test_control',''...
			,'redPath',{{}}...
			,'yelPath',{{}}...
			,'timeline',zeros(1,3)...
			,'timeStep',[]...
			,'yelInsideOverT',[]...
			,'redMaskChange',[]...
			,'maxGradIodine',[]...
			,'maxGradLocation',[]...
			);

wellStructArray(1:pathN,1) = imageTemplate;

for i=1:pathN
	wellStructArray(i).conditionStr		= conditionArray{i};
	wellStructArray(i).test_control		= test_controlArray{i};
	wellStructArray(i).redPath					= redPathArray(i,:);
	wellStructArray(i).yelPath					= yelPathArray(i,:);
	wellStructArray(i).timeline(:,:)		= timelineArray(i,:);
	wellStructArray(i).timeStep				= timeStepArray(i);
end

end

