function  input = createInputStruct_local( inputFolderN )
%CREATE_INPUT_STRUCT_LOCAL create empty structs for each input folder,
%with the appropriate properties.

inputTemplate = struct(...
			'plateStr',[]...
			,'experimentStr',[]...
			,'folderName',[]...
			,'baseFolder',[]...
			,'filePrefix',[]...
			,'conditionStr',{{}} ...
			,'condWells',{{}}...
			,'normConditionStr',[]...
			,'pixelBinning',[]...
			,'siteN',[]...
		);

for i=1:inputFolderN
	
	input(i) = inputTemplate;
	
end

end
