function  imageStruct = createImageStruct( conditionArray, ...
	binningArray,redPathArray,yelPathArray )
%CREATE_IMAGE_STRUCT initializes empty structs for each localisation image
%   Defines all attributes of image struct and assigns initial data
%   to appropriate attributes.

pathN = length(redPathArray);
imageTemplate = struct(...
			'conditionStr',''...
			,'redPath',''...
			,'yelPath',''...
			,'binning',[]...
			,'boundingBox',[] ...
			,'cellLocation',{{}}...
			,'redEntire',[]...
			,'redOutside',[]...
			,'yelEntire',[]...
			,'yelOutside',[]...
			,'yelMembrane',[]...
			,'yelInterior',[]...
			,'yelMembraneAbsolute',[]...
      ,'yelEntireAbsolute',[]...
      ,'redEntireAbsolute',[]...
			,'redBackground',[]...
			,'yelBackground',[]...
			,'cellN',[] ...
			);

imageStruct(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStruct(i).redPath			= redPathArray{i};
	imageStruct(i).yelPath			= yelPathArray{i};
	imageStruct(i).conditionStr	= conditionArray{i};
	imageStruct(i).binning			= binningArray{i};
end

end

