function  imageStruct = createImageLocalStruct( conditionArray, ...
	plateStrArray,binningArray,redPathArray , yelPathArray )
%CREATE_IMAGE_LOCAL_STRUCT initializes empty structs for each localisation image
%   Defines all attributes of image_local struct and assigns initial data
%   to appropriate attributes.

pathN = length(redPathArray);
imageTemplate = struct(...
			'condition',''...
			,'plateStr',''...
			,'redPath',''...
			,'yelPath',''...
			,'binning',[]...
			,'boundingBox',[] ...
			,'cellLocation',{{}}...
			,'redEntire',[]...
			,'redOutside',[]...
			,'yelEntire',[]...
			,'yelOutside',[]...
			,'yelMembrane',[]...
			,'yelInterior',[]...
			,'yelMembraneAbsolute',[]...
      ,'yelEntireAbsolute',[]...
      ,'redEntireAbsolute',[]...
			,'redBackground',[]...
			,'yelBackground',[]...
			,'cellN',[] ...
			);

imageStruct(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStruct(i).redPath		= redPathArray{i};
	imageStruct(i).yelPath		= yelPathArray{i};
	imageStruct(i).condition	= conditionArray{i};
 	imageStruct(i).plateStr		= plateStrArray{i};
	imageStruct(i).binning		= binningArray(i);
end

end

