function  input = createInputStruct_quench( inputFolderN )
%CREATE_INPUT_STRUCT_QUENCH create empty structs for each input folder,
%with the appropriate properties.

inputTemplate = struct(...
			'plateStr',[]...
			,'experimentStr',[]...
			,'folderName',[]...
			,'baseFolder',[]...
			,'filePrefix',[]...
			,'conditionStr',{{}} ...
			,'condWells',{{}}...
			,'condWellsControl',{{}}...
			,'timeStep',[]...
			,'timeline',[]...
		);

for i=1:inputFolderN
	
	input(i) = inputTemplate;
	
end

end
