function  imageStruct = createImageLocalStruct( mutationArray...
	,redPathArray , yelPathArray )
%CREATE_IMAGE_LOCAL_STRUCT initializes empty structs for each localisation image
%   Defines all attributes of image_local struct and assigns initial data
%   to appropriate attributes.

pathN = length(redPathArray);
imageTemplate = struct(...
			'mutation',''...
			,'redPath',''...
			,'yelPath',''...
			,'boundingBox',[] ...
			,'cellLocation',[]...
			,'redEntire',[]...
			,'redOutside',[]...
			,'yelEntire',[]...
			,'yelOutside',[]...
			,'yelMembrane',[]...
			,'yelInterior',[]...
			,'redBackground',[]...
			,'yelBackground',[]...
			,'cellN',[] ...
			);

imageStruct(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStruct(i).redPath	= redPathArray{i};
	imageStruct(i).yelPath	= yelPathArray{i};
	imageStruct(i).mutation	= mutationArray{i};
end

end

