function imageStructArray = createImageQuenchStruct(...
	conditionArray,plateStrArray,test_controlArray,timelineArray...
	,frequencyArray,redPathArray,yelPathArray)
%CREATE_IMAGE_QUENCH_STRUCT initializes empty struct for each quench well
%   Defines all attributes of image_quench struct and assigns initial data
%   to appropriate attributes.

pathN = size(redPathArray,1);

imageTemplate = struct(...
			'condition',''...
			,'plateStr',''...
			,'test_control',''...
			,'redPath',{{}}...
			,'yelPath',{{}}...
			,'timeline',zeros(1,3)...
			,'sampleFrequency',[]...
			,'yelInsideOverT',[]...
			,'redMaskChange',[]...
			,'maxGradIodine',[]...
			,'maxGradLocation',[]...
			);

imageStructArray(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStructArray(i).condition				= conditionArray{i};
	imageStructArray(i).plateStr				= plateStrArray{i};
	imageStructArray(i).test_control		= test_controlArray{i};
	imageStructArray(i).redPath					= redPathArray(i,:);
	imageStructArray(i).yelPath					= yelPathArray(i,:);
	imageStructArray(i).timeline(:,:)		= timelineArray(i,:);
	imageStructArray(i).sampleFrequency	= frequencyArray(i);
end

end

